// <auto-generated />
using MVCBasics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCBasics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220530180007_Seeded some persons")]
    partial class Seededsomepersons
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCBasics.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            City = "Trollhättan",
                            Name = "Adam Andersson",
                            PhoneNumber = "031445511"
                        },
                        new
                        {
                            PersonId = 2,
                            City = "Göteborg",
                            Name = "Bengt Bengtsson",
                            PhoneNumber = "031548422"
                        },
                        new
                        {
                            PersonId = 3,
                            City = "Stockholm",
                            Name = "Cesar Cederquist",
                            PhoneNumber = "031443433"
                        },
                        new
                        {
                            PersonId = 4,
                            City = "Göteborg",
                            Name = "David Dalquist",
                            PhoneNumber = "0314434242"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
